#PROJETO SIMWS
#CONTEM API COM BANCO DE DADOS SQLITE EM MEMORIA
#Execute o comando a seguir na raiz do projeto para criar as imagens:
#>docker-compose up -d --build
#Para enviar as imagens para o docker-hub
#>docker-compose push
version: "3.8"
services:
  simws:
    restart: always
    #environment:
    #  - SIMWS_DBSOURCE=./database/verbos.db
    #  - SIMWS_API_PORT=8080
    container_name: "simws"
    build: 
      context: .
      dockerfile: Dockerfile
    image: gutoconde/simws:1.0
    ports:
      - "8080:8080"