AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Servicos do aplicativo SIM

Resources:
  simws:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.gutoconde.simws.StreamLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: target/simws-0.0.1-SNAPSHOT-lambda-package.zip
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  simws:
    Description: URL da aplicacao
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/simws'
    Export:
      Name: simws