DROP TABLE IF EXISTS SERVIDOR;
DROP TABLE IF EXISTS HISTORICOVENCIMENTOCARGO;
DROP TABLE IF EXISTS CARGO;
DROP TABLE IF EXISTS GABINETE;

CREATE TABLE GABINETE (
	ID INTEGER,
	CODIGO VARCHAR(50),
	NOME VARCHAR(255),
	PRIMARY KEY (ID),
	UNIQUE(CODIGO)
);

CREATE TABLE CARGO(
	ID INTEGER,
	CODIGO VARCHAR(20),
	PRIMARY KEY(ID),
	UNIQUE(CODIGO)
);

CREATE TABLE SERVIDOR (
	ID INTEGER,
	PONTO VARCHAR(20),
	NOME VARCHAR(255),
	IDGABINETE INTEGER,
	CODIGOCARGO VARCHAR(20),
	PRIMARY KEY (ID),
	FOREIGN KEY (IDGABINETE) REFERENCES GABINETE(ID),
	UNIQUE(PONTO)
);

CREATE TABLE HISTORICOVENCIMENTOCARGO(
	ID INTEGER,
	IDCARGO INTEGER,
	VENCIMENTO FLOAT(10,2) NOT NULL,
	GRG FLOAT(10,2) NOT NULL,
	DATAINICIO TEXT NOT NULL,
	DATAFIM TEXT,
	DATACANCELAMENTO TEXT,
	PRIMARY KEY (ID),
	FOREIGN KEY (IDCARGO) REFERENCES CARGO(ID)
);